options:
  formatter: stylish
  merge-default-rules: true
  cache-config: true
rules:
  no-ids: 0
  no-qualifying-elements: 0
  no-vendor-prefixes: 0
  class-name-format:
    - 1
    - convention: hyphenatedlowercase
  property-sort-order:
    - 1
    - order: alphabetical
  force-attribute-nesting: 0
  hex-notation:
    - 1
    - style: lowercase
  mixins-before-declarations: 0
  nesting-depth:
    - 1
    - max-depth: 3
  no-color-keywords: 0
  no-important: 0
  no-mergeable-selectors: 1
  no-trailing-whitespace: 1
  no-transition-all: 0
  property-units:
    - 1
    - global:
        - "em"
        - "rem"
        - "s"
        - "ms"
        - "%"
        - "deg"
        - "vh"
        - "vw"
  quotes:
    - 1
    - style: single
  single-line-per-selector:
    - 1
    - single-line: true
  space-before-brace:
    - 1
    - style: "1tbs"
  trailing-semicolon:
    - 1
    - include: true
  variable-name-format:
    - 1
    - allow-leading-underscore: true
    - convention: hyphenatedlowercase
  zero-unit:
    - 1
    - include: false
