pipelines:
  branches:
    main:
      - step:
          name: prod-build
          image: ubuntu
          script:
            - apt-get update
            - apt-get install openssh-client -y
            - chmod 400 ./key.pem
            - ssh -i ./key.pem -o StrictHostKeyChecking=no ubuntu@"$INSTANCE_IP_ADDRESS" 'cd ~/repo/takeitnow_frontend && git checkout main && git pull origin main && docker build --file Dockerfile.prod -t takeitnow_frontend_prod . && docker stop takeitnow_frontend_prod && docker rm takeitnow_frontend_prod && docker-compose -f docker-compose.prod.yml up -d && docker system prune -a -f'
    dev:
      - step:
          name: test-build
          image: ubuntu
          script:
            - apt-get update
            - apt-get install openssh-client -y
            - chmod 400 ./key.pem
            - ssh -i ./key.pem -o StrictHostKeyChecking=no ubuntu@"$INSTANCE_IP_ADDRESS" 'cd ~/repo/takeitnow_frontend && git checkout dev && git pull origin dev && docker build --file Dockerfile.dev -t takeitnow_frontend_dev . && docker stop takeitnow_frontend_dev && docker rm takeitnow_frontend_dev && docker-compose -f docker-compose.dev.yml up -d && docker system prune -a -f'
