pipelines:
  default:
      - step:
          name: Eslint and Stylelint
          image: ubuntu
          script:
            - apt-get update && apt-get install -y git unzip curl
            - curl -sL https://deb.nodesource.com/setup_14.x | bash -
            - apt-get install -y nodejs
            - git clone $BITBUCKET_CLONE_DIR /app
            - cd app
            - git checkout $BITBUCKET_BRANCH
            - npm install
            - npm run lint
  branches:
    main:
      - step:
          name: prod-build
          image: ubuntu
          script:
            - apt-get update
            - apt-get install openssh-client -y
            - chmod 400 ./key.pem
            - ssh -i ./key.pem -o StrictHostKeyChecking=no ubuntu@"$INSTANCE_IP_ADDRESS" 'cd ~/repo/takeitnow_frontend && git checkout main && git pull origin main && docker stop takeitnow_frontend_prod && docker rm takeitnow_frontend_prod && docker system prune -a -f && docker-compose -f docker-compose.prod.yml --project-name takeitnow-prod up -d && docker system prune -a -f'
    dev:
      - step:
          name: test-build
          image: ubuntu
          script:
            - apt-get update
            - apt-get install openssh-client -y
            - chmod 400 ./key.pem
            - ssh -i ./key.pem -o StrictHostKeyChecking=no ubuntu@"$INSTANCE_IP_ADDRESS" 'cd ~/repo/takeitnow_frontend && git checkout dev && git pull origin dev && docker stop takeitnow_frontend_dev && docker rm takeitnow_frontend_dev && docker system prune -a -f && docker-compose -f docker-compose.dev.yml --project-name takeitnow-dev up -d'
