pipelines:
  branches:
    main:
      - step:
          name: prod-build
          image: ubuntu
          script:
            - apt-get update
            - apt-get install openssh-client -y
            - chmod 400 ./key.pem
            - ssh -i ./key.pem -o StrictHostKeyChecking=no ubuntu@"$INSTANCE_IP_ADDRESS" 'cd ~/repo/takeitnow_frontend && git checkout main && git pull origin main && docker-compose -f docker-compose.prod.yml --project-name takeitnow-prod up -d && docker system prune -a -f'
    dev:
      - step:
          name: test-build
          image: ubuntu
          script:
            - apt-get update
            - apt-get install openssh-client -y
            - chmod 400 ./key.pem
            - ssh -i ./key.pem -o StrictHostKeyChecking=no ubuntu@"$INSTANCE_IP_ADDRESS" 'cd ~/repo/takeitnow_frontend && git checkout dev && git pull origin dev && docker-compose -f docker-compose.dev.yml --project-name takeitnow-dev up -d && docker system prune -a -f'
