pipelines:
  default:
    - step:
        name: SSH into EC2 Instance
        image: ubuntu
        script:
          - apt-get update
          - apt-get install openssh-client -y
          - chmod 400 ./key.pem
          - ssh -i ./key.pem -o StrictHostKeyChecking=no ubuntu@"$INSTANCE_IP_ADDRESS" 'cd ~/repo/takeitnow_frontend && git pull origin main && docker build -t takeitnow_frontend . && docker-compose up -d && docker system prune -a -f'